### ISSUE TITLE
ImportError: cannot import name 'gradio' from 'modules.utils' 

### ISSUE THREAD

**Issue by luthis1124** [wsippel/bark_tts#20]
ERROR:Failed to load the extension "bark_tts".
Traceback (most recent call last):
  File "/home/st/GIT/oobabooga_linux_2/text-generation-webui/modules/extensions.py", line 34, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "/home/st/GIT/oobabooga_linux_2/text-generation-webui/extensions/bark_tts/script.py", line 3, in <module>
    from modules.utils import gradio
ImportError: cannot import name 'gradio' from 'modules.utils' (/home/st/GIT/oobabooga_linux_2/text-generation-webui/modules/utils.py)

**Comment by luthis1124** [comment]
fixed by updating to latest oobabooga
