### ISSUE TITLE
doesn't work with latest oobabooga

### ISSUE THREAD

**Issue by rktvr** [wsippel/bark_tts#23]
fresh ooba install (1.6.1) and I get this on launching:

```
Traceback (most recent call last):
  File "E:\oobabooga\text-generation-webui-1.6.1\server.py", line 229, in <module>
    create_interface()
  File "E:\oobabooga\text-generation-webui-1.6.1\server.py", line 140, in create_interface
    extensions_module.create_extensions_block()  # Extensions block
  File "E:\oobabooga\text-generation-webui-1.6.1\modules\extensions.py", line 192, in create_extensions_block
    extension.ui()
  File "E:\oobabooga\text-generation-webui-1.6.1\extensions\bark_tts\script.py", line 243, in ui
    chat.save_persistent_history, gradio('history', 'character_menu', 'mode'), None).then(
AttributeError: module 'modules.chat' has no attribute 'save_persistent_history'
```

**Comment by HanJammer** [comment]
Same issue here.

**Comment by carinae** [comment]
Same here, tts extension need to be updated since save_persistent_history has been removed
[watch here](https://github.com/oobabooga/text-generation-webui/issues/4037)

**Comment by wsippel** [comment]
Should be fixed now.
