### ISSUE TITLE
[issue] cannot run extension with bark_tts

### ISSUE THREAD

**Issue by anyshu** [wsippel/bark_tts#4]
python server.py --extension bark_tts
Gradio HTTP request redirected to localhost :)
bin /home/mt/Downloads/ENTER/envs/tts-generation/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda116_nocublaslt.so
[nltk_data] Downloading package punkt to /home/mt/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
Loading the extension "bark_tts"... 
Loading Bark models...
Ok.
Traceback (most recent call last):
  File "/home/mt/ai/text-generation-webui/server.py", line 922, in <module>
    create_interface()
  File "/home/mt/ai/text-generation-webui/server.py", line 715, in create_interface
    extensions_module.create_extensions_block()
  File "/home/mt/ai/text-generation-webui/modules/extensions.py", line 119, in create_extensions_block
    extension.ui()
  File "/home/mt/ai/text-generation-webui/extensions/bark_tts/script.py", line 208, in ui
    convert_confirm.click(remove_tts_from_history, [shared.gradio[k] for k in ['name1', 'name2', 'mode']], shared.gradio['display'])
  File "/home/mt/ai/text-generation-webui/extensions/bark_tts/script.py", line 208, in <listcomp>
    convert_confirm.click(remove_tts_from_history, [shared.gradio[k] for k in ['name1', 'name2', 'mode']], shared.gradio['display'])
KeyError: 'name1'

**Comment by wsippel** [comment]
Sorry for the confusion. This extension, just like several of Oobabooga's built-in extensions, only works in chat mode. I should probably add that to instructions and troubleshooting section.

**Comment by anyshu** [comment]
ok, I see. Thank you!
