### ISSUE TITLE
Error when trying to chat 

### ISSUE THREAD

**Issue by if-ai** [wsippel/bark_tts#5]
I got this error 

Loaded the model in 9.40 seconds.
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\uzr\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
Loading the extension "bark_tts"...
Loading Bark models...
Ok.
Starting streaming server at ws://0.0.0.0:5005/api/v1/stream
Loading the extension "gallery"... Ok.
Starting API at http://0.0.0.0:5000/api
Running on local URL:  http://0.0.0.0:7861

To create a public link, set `share=True` in `launch()`.
Output generated in 14.34 seconds (8.02 tokens/s, 115 tokens, context 1848, seed 1433429931)
```
Traceback (most recent call last):
  File "E:\oobabooga-windows\installer_files\env\lib\site-packages\gradio\routes.py", line 395, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\oobabooga-windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1193, in process_api
    result = await self.call_function(
  File "E:\oobabooga-windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 930, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\oobabooga-windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\oobabooga-windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\oobabooga-windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\oobabooga-windows\installer_files\env\lib\site-packages\gradio\utils.py", line 491, in async_iteration
    return next(iterator)
  File "E:\oobabooga-windows\text-generation-webui\modules\chat.py", line 247, in cai_chatbot_wrapper
    for history in chatbot_wrapper(text, state):
  File "E:\oobabooga-windows\text-generation-webui\modules\chat.py", line 187, in chatbot_wrapper
    visible_reply = apply_extensions("output", visible_reply)
  File "E:\oobabooga-windows\text-generation-webui\modules\extensions.py", line 115, in apply_extensions
    return EXTENSION_MAP[typ](*args, **kwargs)
  File "E:\oobabooga-windows\text-generation-webui\modules\extensions.py", line 61, in _apply_string_extensions
    text = getattr(extension, function_name)(text)
  File "E:\oobabooga-windows\text-generation-webui\extensions\bark_tts\script.py", line 167, in output_modifier
    audio_chunk = generate_audio(chunk, history_prompt=params['speaker'], text_temp=params['text_temp'], waveform_temp=params['waveform_temp'])
  File "E:\oobabooga-windows\installer_files\env\lib\site-packages\bark\api.py", line 107, in generate_audio
    semantic_tokens = text_to_semantic(
  File "E:\oobabooga-windows\installer_files\env\lib\site-packages\bark\api.py", line 25, in text_to_semantic
    x_semantic = generate_text_semantic(
  File "E:\oobabooga-windows\installer_files\env\lib\site-packages\bark\generation.py", line 406, in generate_text_semantic
    assert len(text.strip()) > 0
AssertionError

```

is weird bc when I loaded Chiharu the introduction message audio got generated but as soon as use input I get errors and via colab works fine windows with AMD processor

**Comment by if-ai** [comment]
the previous version of the script works but it doesn't produce more than 12secs of audio also has an error 
Starting the web UI...
Gradio HTTP request redirected to localhost :)
Loading alpaca-native-4bit...
Found the following quantized model: models\alpaca-native-4bit\alpaca7b-4bit.pt
Loading model ...
Done.
Loaded the model in 8.15 seconds.
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\uzr\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
Loading the extension "bark_tts"... Ok.
Starting streaming server at ws://0.0.0.0:5005/api/v1/stream
Loading the extension "IF_SD_api"... Starting API at http://0.0.0.0:5000/api
Ok.
Loading the extension "gallery"... Ok.
Running on local URL:  http://0.0.0.0:7861
```

To create a public link, set `share=True` in `launch()`.
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "E:\oobabooga-windows\installer_files\env\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "E:\oobabooga-windows\installer_files\env\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```
100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [00:14<00:00,  6.96it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 32/32 [00:41<00:00,  1.30s/it]
```
Output generated in 154.59 seconds (1.29 tokens/s, 200 tokens, context 1848, seed 1636367863)
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "E:\oobabooga-windows\installer_files\env\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "E:\oobabooga-windows\installer_files\env\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```

**Comment by wsippel** [comment]
Can't test it myself right now, and I have no idea what either error could be about from just the error messages alone. The second issue looks API related, so maybe try again without API support. Also, the 12-15 second limit is a technical limitation of Bark itself as explained in the Readme. I have no idea what you mean by "previous version", but if you're referring to my extension, early versions didn't have the tokenizer to work around this limit. The tokenizer should be enabled by default, but make sure the checkbox is there and the feature is turned on.

**Comment by if-ai** [comment]
Yes, I ran it without any flag but chat and it works but is a real bummer since I want to use it with the SD_API over the networks so I will have to find another way. Thank you.

**Comment by wsippel** [comment]
So I've tested it myself, and it does work just fine for me with the API enabled. Might be a Windows-specific issue.

**Comment by if-ai** [comment]
I spoke too soon It did generate one text for the introduction then one for
the next message and then it went to the same error when I tried a second
input message.
I reinstalled did everything but it fails.

The notebook running from the ooga environment works well. I generated
audio and even trained a voice.
It looks from the error that is something to do with the Cai wrapper.

Thanks.

**Comment by if-ai** [comment]
I think is because nltk has a problem with my formatted text. I made a character that makes prompts for SD. It formats it's replies as non-verbose and separated by comas, with parenthesis and : to weight the words. It always fails when I use the character but with other characters or in Notebook works perfect. I have a link for my character if you want to try it out here https://civitai.com/user/impactframes/models  I made a video where I use bard here https://youtu.be/u_5ZyWZRClU?t=501 and as you can see it works wonderfully just my character has this problem

**Comment by if-ai** [comment]
*bark
