### ISSUE TITLE
Cant Launch 

### ISSUE THREAD

**Issue by ameen-roayan** [wsippel/bark_tts#6]
Hello 

Getting this error on launch

Traceback (most recent call last):
  File "E:\AI\oobabooga-windows\text-generation-webui\server.py", line 927, in <module>
    create_interface()
  File "E:\AI\oobabooga-windows\text-generation-webui\server.py", line 845, in create_interface
    extensions_module.create_extensions_block()
  File "E:\AI\oobabooga-windows\text-generation-webui\modules\extensions.py", line 133, in create_extensions_block
    extension.ui()
  File "E:\AI\oobabooga-windows\text-generation-webui\extensions\bark_tts\script.py", line 222, in ui
    convert_confirm.click(remove_tts_from_history, [shared.gradio[k] for k in ['name1', 'name2', 'mode']], shared.gradio['display'])
  File "E:\AI\oobabooga-windows\text-generation-webui\extensions\bark_tts\script.py", line 222, in <listcomp>
    convert_confirm.click(remove_tts_from_history, [shared.gradio[k] for k in ['name1', 'name2', 'mode']], shared.gradio['display'])
KeyError: 'name1'
Press any key to continue . . .

**Comment by wsippel** [comment]
Looks like you're not running Oobabooga in chat mode. The troubleshooting on the Github page explains how to start the web UI in chat mode.

**Comment by wsippel** [comment]
The extension should work in all modes now.
